export const translations = {
  EN: {
    billedFrom: "Billed From",
    billedTo: "Billed To",
    invoiceNo: "Invoice No",
    date: "Date",
    dueDate: "Due Date",
    description: "Description",
    qty: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    bankDetails: "Bank Details",
    holder: "Account Holder",
    number: "Account Number",
    ifsc: "IFSC Code",
    terms: "Terms & Remarks",
    status: "Status",
    company: "Company",
    address: "Address",
    phone: "Phone",
    email: "Email",
    gst: "GSTIN",
    sendTo: "Send To",
    invoiceDetails: "Invoice Details",
    termsOfPayment: "Terms of Payment",
    dueOnReceipt: "Due on Receipt"
  },
  ES: {
    billedFrom: "Facturado Por",
    billedTo: "Facturado A",
    invoiceNo: "Factura N°",
    date: "Fecha",
    dueDate: "Fecha de Vencimiento",
    description: "Descripción",
    qty: "Cant",
    rate: "Tarifa",
    amount: "Importe",
    subtotal: "Subtotal",
    tax: "Impuesto",
    total: "Total",
    bankDetails: "Datos Bancarios",
    holder: "Titular",
    number: "Número de Cuenta",
    ifsc: "Código IFSC",
    terms: "Términos y Observaciones",
    status: "Estado",
    company: "Empresa",
    address: "Dirección",
    phone: "Teléfono",
    email: "Correo",
    gst: "NIF/CIF",
    sendTo: "Enviar A",
    invoiceDetails: "Detalles de la Factura",
    termsOfPayment: "Condiciones de Pago",
    dueOnReceipt: "Pago al Recibir"
  },
  FR: {
    billedFrom: "Facturé Par",
    billedTo: "Facturé À",
    invoiceNo: "Facture N°",
    date: "Date",
    dueDate: "Date d'Échéance",
    description: "Description",
    qty: "Qté",
    rate: "Tarif",
    amount: "Montant",
    subtotal: "Sous-total",
    tax: "Taxe",
    total: "Total",
    bankDetails: "Coordonnées Bancaires",
    holder: "Titulaire",
    number: "Numéro de Compte",
    ifsc: "Code IFSC",
    terms: "Conditions & Remarques",
    status: "Statut",
    company: "Entreprise",
    address: "Adresse",
    phone: "Téléphone",
    email: "E-mail",
    gst: "TVA",
    sendTo: "Envoyer À",
    invoiceDetails: "Détails de la Facture",
    termsOfPayment: "Conditions de Paiement",
    dueOnReceipt: "Dû à la Réception"
  },
  DE: {
    billedFrom: "Rechnungssteller",
    billedTo: "Rechnungsempfänger",
    invoiceNo: "Rechnungsnr.",
    date: "Datum",
    dueDate: "Fälligkeitsdatum",
    description: "Beschreibung",
    qty: "Menge",
    rate: "Satz",
    amount: "Betrag",
    subtotal: "Zwischensumme",
    tax: "Steuer",
    total: "Gesamtsumme",
    bankDetails: "Bankverbindung",
    holder: "Kontoinhaber",
    number: "Kontonummer",
    ifsc: "IFSC-Code",
    terms: "Bedingungen & Bemerkungen",
    status: "Status",
    company: "Firma",
    address: "Adresse",
    phone: "Telefon",
    email: "E-mail",
    gst: "USt-IdNr.",
    sendTo: "Senden An",
    invoiceDetails: "Rechnungsdetails",
    termsOfPayment: "Zahlungsbedingungen",
    dueOnReceipt: "Fällig bei Erhalt"
  },
  HI: {
    billedFrom: "प्रेषक",
    billedTo: "प्राप्तकर्ता",
    invoiceNo: "चालान संख्या",
    date: "तारीख",
    dueDate: "देय तिथि",
    description: "विवरण",
    qty: "मात्रा",
    rate: "दर",
    amount: "रकम",
    subtotal: "उपयोग",
    tax: "कर",
    total: "कुल",
    bankDetails: "बैंक विवरण",
    holder: "खाताधारक",
    number: "खाता संख्या",
    ifsc: "आईएफएससी कोड",
    terms: "नियम और शर्तें",
    status: "स्थिति",
    company: "कंपनी",
    address: "पता",
    phone: "फ़ोन",
    email: "ईमेल",
    gst: "जीएसटी नंबर",
    sendTo: "सेवा में",
    invoiceDetails: "चालान विवरण",
    termsOfPayment: "भुगतान की शर्तें",
    dueOnReceipt: "प्राप्ति पर देय"
  }
};

const currencySymbols = {
  INR: "₹",
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "A$",
  CAD: "C$",
};

export const formatInvoiceData = (invoiceData) => {
    const {
        id = "",
        title,
        company = {},
        invoice = {},
        account = {},
        billing = {},
        shipping = {},
        tax = 0,
        notes = "",
        items = [],
        logo = "",
        paymentLink = "",
        currency = "INR",
        language = "EN",
        isRecurring = false,
        recurringInterval = "MONTHLY",
        recurrenceStatus = "ACTIVE",
        themeColor = "#0d6efd"
    } = invoiceData || {};

    const currencySymbol = currencySymbols[currency] || "₹";
    const t = translations[language] || translations.EN;

    const subtotal = items.reduce((acc, item) => acc + (item.qty * item.amount), 0);
    const taxAmount = subtotal * (tax / 100);
    const total = subtotal + taxAmount;

    return {
        id,
        title,
        companyName: company.name,
        companyAddress: company.address,
        companyPhone: company.phone,
        companyEmail: company.email,
        companyGst: company.gst,
        companyLogo: logo,

        invoiceNumber: invoice.number,
        invoiceDate: invoice.date,
        paymentDate: invoice.dueDate,

        accountName: account.name,
        accountNumber: account.number,
        accountIfscCode: account.ifsccode,

        billingName: billing.name,
        billingAddress: billing.address,
        billingPhone: billing.phone,
        billingEmail: billing.email,

        shippingName: shipping.name,
        shippingAddress: shipping.address,
        shippingPhone: shipping.phone,

        currencySymbol,
        currency,
        language,
        isRecurring,
        recurringInterval,
        recurrenceStatus,
        themeColor,

        tax,
        items,
        notes,
        subtotal,
        taxAmount,
        total,
        paymentLink,
        t
    };
};

export const formatDate = (dateStr) => {
  if (!dateStr) return "N/A";

  const date = new Date(dateStr);
  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};